### Upload Picture
POST {{baseUrl}}/image
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{accessToken}}

--boundary
Content-Disposition: form-data; name="file"; filename="image.jpg"

// The 'image.jpg' file will be uploaded
< ./resources/image.jpg
--boundary
