### Create Product
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "new product 16",
  "description": "prod descsdfsdf",
  "category": "Electronics/Audio",
  "pricePerDay": 1,
  "condition": "NEU",
  "pictureIds": [
    "123", "456"
  ]
}

### Create Invalid Product
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "new product 16",
  "description": "prod descsdfsdf",
  "category": "Electronics/Audio",
  "condition": "NEU",
  "pictureIds": [
    "123", "456"
  ]
}

### Get Product Categories
GET {{baseUrl}}/products/categories
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Get Product Conditions
GET {{baseUrl}}/products/conditions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Get Product By Id
GET {{baseUrl}}/products/6214e5bdefb9b73d45575293
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Get Products Of User
GET {{baseUrl}}/product
Content-Type: application/json
Authorization: Bearer {{accessToken}}